module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '😘', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💗'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/Hkl27CXZ1s6A9TVt8kN8id',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/od7koi.jpg',
    NEWSLETTER_JID: '120363421408345374@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'LITHULI MD',
    OWNER_NAME: 'Cᴇᴛʜᴀɴᴀ',
    OWNER_NUMBER: '94776532488',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © ᴏᴡɴᴇʀ ʙʏ ◈Cᴇᴛʜᴀɴᴀ │ᴀᴅᴍɪɴ ʙʏ Lᴇʜᴀʀᴀ│Dɪʟꜱʜᴀɴ |  Sᴀɴᴜ xᴅ🐦‍🔥',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbBrdrQDzgTKjwWJwn3A',
};
